In [ ]:
import pandas as pd

ЭТАП 1: Анализ данных (EDA)
Загрузка и базовая обработка

In [ ]:
#1.	Загрузить датасет (из Kaggle или другого источника) и вывести первые 10 строк.
df = pd.read_csv('StudentsPerformance (2).csv')

In [ ]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:
#2.	Посмотреть .info(), .shape, .describe().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.describe().round()

       math score  reading score  writing score
count      1000.0         1000.0         1000.0
mean         66.0           69.0           68.0
std          15.0           15.0           15.0
min           0.0           17.0           10.0
25%          57.0           59.0           58.0
50%          66.0           70.0           69.0
75%          77.0           79.0           79.0
max         100.0          100.0          100.0

In [ ]:
df.size

8000

In [ ]:
#3.	Вывести список колонок и их типы.
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [ ]:
#4.	Проверить на пропущенные значения.
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df = df.rename(columns={'race/ethnicity': 'race_ethnicity', 'parental level of education': 'parental_level_of_education',
                   'test preparation course': 'test_preparation_course', 'math score': 'math_score',
                        'reading score': 'reading_score','writing score': 'writing_score'})

In [ ]:
#5.	Сохранить очищенный датафрейм в students_clean.csv.
df.to_csv('students_clean.csv', sep=',', index=False)

In [ ]:
df

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

Pandas (20 задач)

In [ ]:
#6.	Сколько уникальных значений у race/ethnicity?
df['race_ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [ ]:
count_race = df['race_ethnicity'].nunique()
print(f'Количество уникальных значений у race/ethnicity = {count_race}')

Количество уникальных значений у race/ethnicity = 5

In [ ]:
#7.	Топ-3 самых высоких средних оценок по математике среди этнических групп.
df['math_score'].sort_values(ascending=False).head(3)

451    100
458    100
962    100
Name: math_score, dtype: int64

In [ ]:
df.groupby('race_ethnicity')['math_score'].mean().round().sort_values(ascending=False).head(3)

race_ethnicity
group E    74.0
group D    67.0
group C    64.0
Name: math_score, dtype: float64

In [ ]:
#8.	Сколько учеников прошли курс подготовки (test preparation course)?
count_completed = (df['test_preparation_course'] == 'completed').sum()
print(f'Количество учеников прошли курс подготовки = {count_completed}')

Количество учеников прошли курс подготовки = 358

In [ ]:
df[df['test_preparation_course'] == 'completed']

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [ ]:
#9.	Средняя оценка по математике среди тех, кто прошел курс.
df.groupby('test_preparation_course')['math_score'].mean().round()

test_preparation_course
completed    70.0
none         64.0
Name: math_score, dtype: float64

In [ ]:
count = df[df['test_preparation_course'] == 'completed']['math_score'].mean().round()
print(f'Средняя оценка по математике среди тех, кто прошел курс = {count}')

Средняя оценка по математике среди тех, кто прошел курс = 70.0

In [ ]:
#10.	Средняя оценка по чтению среди учеников с бесплатным питанием (lunch == free/reduced).
count_free = df[df['lunch'] == 'free/reduced']['reading_score'].mean().round()
print(f'Средняя оценка по чтению среди учеников с бесплатным питанием = {count_free}')

Средняя оценка по чтению среди учеников с бесплатным питанием = 65.0

In [ ]:
df.groupby('lunch')['reading_score'].mean().round()

lunch
free/reduced    65.0
standard        72.0
Name: reading_score, dtype: float64

In [ ]:
#11.	Сколько учеников с уровнем образования родителей bachelor's degree?
(df['parental_level_of_education'] == "bachelor's degree").sum()

np.int64(118)

In [ ]:
#12.	Средние баллы по всем предметам по полу (gender).
df.groupby('gender') ['math_score'].mean().round()

gender
female    64.0
male      69.0
Name: math_score, dtype: float64

In [ ]:
df.groupby('gender') ['reading_score'].mean().round()

gender
female    73.0
male      65.0
Name: reading_score, dtype: float64

In [ ]:
df.groupby('gender') ['writing_score'].mean().round()

gender
female    72.0
male      63.0
Name: writing_score, dtype: float64

In [ ]:
df.groupby('gender') [['math_score', 'writing_score', 'reading_score']].mean().round()

        math_score  writing_score  reading_score
gender
female        64.0           72.0           73.0
male          69.0           63.0           65.0

In [ ]:
#13.	У кого медианная оценка по письму выше — мужчины или женщины?
df.groupby('gender') ['writing_score'].median().round()

gender
female    74.0
male      64.0
Name: writing_score, dtype: float64

In [ ]:
#14.	Средний балл по математике по уровню образования родителей.
df.groupby('parental_level_of_education') ['math_score'].mean().round().sort_values(ascending=False)

parental_level_of_education
master's degree       70.0
bachelor's degree     69.0
associate's degree    68.0
some college          67.0
some high school      63.0
high school           62.0
Name: math_score, dtype: float64

In [ ]:
#15.	Группировка по test preparation course и lunch + средние оценки.
df.groupby(['test_preparation_course','lunch'])[['math_score', 'writing_score', 'reading_score']].mean().round()

                                      math_score  writing_score  reading_score
test_preparation_course lunch
completed               free/reduced        63.0           70.0           70.0
                        standard            74.0           77.0           76.0
none                    free/reduced        57.0           59.0           62.0
                        standard            68.0           68.0           69.0

In [ ]:
#16.	Найти самого успешного ученика (максимум по сумме 3 оценок).
df['all_score'] = df['math_score'] +  df['reading_score'] + df['reading_score']

In [ ]:
df['all_score'].max()

300

In [ ]:
(df['all_score'] == 300).sum()

np.int64(4)

In [ ]:
df[df['all_score'] == 300]

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,all_score
149,male,group E,associate's degree,free/reduced,completed,100,100,93,300
458,female,group E,bachelor's degree,standard,none,100,100,100,300
916,male,group E,bachelor's degree,standard,completed,100,100,100,300
962,female,group E,associate's degree,standard,none,100,100,100,300

In [ ]:
#17.	У скольких учеников math score >= 90?
(df['math_score'] >= 90).sum()

np.int64(58)

In [ ]:
#18.	У скольких учеников все три оценки больше 80?
((df['math_score'] > 80) & (df['reading_score'] > 80) & (df['writing_score'] > 80)).sum()

np.int64(110)

In [ ]:
#19.	Группировка по gender, race/ethnicity, mean().
df.groupby(['gender', 'race_ethnicity'])[['math_score', 'writing_score', 'reading_score']].mean().round()

                       math_score  writing_score  reading_score
gender race_ethnicity
female group A               59.0           68.0           69.0
       group B               61.0           70.0           71.0
       group C               62.0           72.0           72.0
       group D               65.0           75.0           74.0
       group E               71.0           76.0           76.0
male   group A               64.0           59.0           62.0
       group B               66.0           60.0           63.0
       group C               68.0           63.0           65.0
       group D               69.0           65.0           66.0
       group E               77.0           67.0           70.0

In [ ]:
#20.	Создать новый столбец average_score = среднее из трех оценок.
df['average_score'] = round(df['all_score'] / 3)
# print(f'Среднея оценка из трех оценок = {avg_count}')

In [ ]:
df

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,all_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,216,72.0
1,female,group C,some college,standard,completed,69,90,88,249,83.0
2,female,group B,master's degree,standard,none,90,95,93,280,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,161,54.0
4,male,group C,some college,standard,none,76,78,75,232,77.0
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,286,95.0
996,male,group C,high school,free/reduced,none,62,55,55,172,57.0
997,female,group C,high school,free/reduced,completed,59,71,65,201,67.0
998,female,group D,some college,standard,completed,68,78,77,224,75.0
999,female,group D,some college,free/reduced,none,77,86,86,249,83.0